baseURL = 'https://stphnwlsh.github.io'
languageCode = 'en-au'
title = 'Stephen Walsh'
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-NZ7C1P4YT0"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Stephen Walsh"
  description = "Personal profile site"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["/css/overrides.css"]
  custom_js  = []

[params.social]
  Github        = "stphnwlsh"
  LinkedIn      = "stphnwlsh"
  Hashnode      = "stphnwlsh"

## Main Menu
[[menu.main]]
  name = "Github"
  identifier = "github"
  weight = 100
  url = "https://github.com/stphnwlsh"
[[menu.main]]
  name = "LinkedIn"
  weight = 200
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/stphnwlsh"
[[menu.main]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "https://stphnwlsh.hashnode.dev"