theme = "lynx"
title = "Stephen Walsh"
languageCode = "en-au"
baseUrl = "https://stphnwlsh.github.io"
googleAnalytics = "G-NZ7C1P4YT0"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  image = "profile.png"
  alternative = "Stephen Walsh | Husband | Father | Software Engineer | Learner | Leader"
  links = [
    { github = "https://github.com/stphnwlsh" },
    { dev = "https://dev.to/stphnwlsh" },
    { twitter = "https://twitter.com/stphnwlsh" },
    { linkedin = "https://www.linkedin.com/in/stphnwlsh" },
    { nuget = { href = "https://www.nuget.org/profiles/stphnwlsh", text = "NuGet" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[params]
  keywords = "stphnwlsh,stephen,walsh,software,engineer,developer,profile,blogger"
  robots = "index,follow"
