theme = "lynx"
title = "Stephen Walsh"
languageCode = "en-au"
baseUrl = "https://stphnwlsh.github.io"
googleAnalytics = "${GOOGLE_ANALYTICS_ID}"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  image = "profile.png"
  alternative = "Stephen Walsh | Husband | Father | Software Engineer | Learner | Leader"
  links = [
    { linkedin = "https://www.linkedin.com/in/stphnwlsh" },
    { github = "https://github.com/stphnwlsh" },
    { medium = "https://medium.com/@stphnwlsh" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[params]
  keywords = "stphnwlsh,stephen,walsh,software,engineer,developer,profile,blogger,learner,leader"
  robots = "index,follow"
