theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  image = "profile.png"
  links = [
    { github = "https://github.com/stphnwlsh" },
    { dev = "https://dev.to/stphnwlsh" },
    { twitter = "https://twitter.com/stphnwlsh" },
    { linkedin = { href = "https://fontawesome.com/" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
