theme = "lynx"
title = "Stephen Walsh"
googleAnalytics = "G-NZ7C1P4YT0"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  image = "profile.png"
  links = [
    { github = "https://github.com/stphnwlsh" },
    { dev = "https://dev.to/stphnwlsh" },
    { twitter = "https://twitter.com/stphnwlsh" },
    { linkedin = { href = "https://www.linkedin.com/in/stphnwlsh" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
